name: ci
on: [push, pull_request]

jobs:
  api-test:
    runs-on: ubuntu-latest
    services:
      weaviate:
        image: semitechnologies/weaviate:latest
        ports: ["8080:8080"]
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      WEAVIATE_URL: "http://localhost:8080"
      WEAVIATE_API_KEY: "test"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - run: pip install -e .[dev]
      - run: pytest -q 